In [1]:
import torch

In [5]:
torch.Tensor([[2, 3], [4, 5], [6, 7]])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]])

In [7]:
torch.LongTensor([[2, 3], [4, 5], [6, 7]])

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [8]:
torch.IntTensor([[2, 3], [4, 5], [6, 7]])

tensor([[2, 3],
        [4, 5],
        [6, 7]], dtype=torch.int32)

In [9]:
torch.zeros((3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
torch.randn((3, 2))

tensor([[-0.9079,  0.7487],
        [ 1.1470, -0.4151],
        [-2.1955,  0.3051]])