# All is Graph

Reference:
1. [图卷积网络到底怎么做，这是一份极简的Numpy实现](https://mp.weixin.qq.com/s/sg9O761F0KHAmCPOfMW_kQ)

## Examples

![Cited from [图卷积网络到底怎么做，这是一份极简的Numpy实现](https://mp.weixin.qq.com/s/sg9O761F0KHAmCPOfMW_kQ)](https://mmbiz.qpic.cn/mmbiz_png/KmXPKA19gW8VBwmtdqsNQQEicrmm06aF2OhU65hickwqmthgLOurE3rpdE2MhZhWo7PzfOK4nz3CicDIyfxv8Wl6Q/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

## GCN

In [2]:
import torch
import numpy as np

### 构建邻接矩阵

In [3]:
A = np.matrix([[0, 1, 0, 1],
               [1, 0, 1, 1],
               [0, 1, 0, 1],
               [1, 1, 1, 0]], dtype=float)

In [4]:
node_features = np.random.rand(4, 6)
node_features

array([[0.49138034, 0.61914356, 0.7810166 , 0.67424675, 0.92683081,
        0.14638454],
       [0.07412095, 0.30862809, 0.94317213, 0.77053792, 0.44166033,
        0.77448924],
       [0.92759974, 0.02146164, 0.9050683 , 0.57438401, 0.20256511,
        0.79205739],
       [0.8582342 , 0.24965293, 0.10441513, 0.23312981, 0.06276997,
        0.62581839]])

In [5]:
A * node_features

matrix([[0.93235515, 0.55828101, 1.04758726, 1.00366773, 0.5044303 ,
         1.40030763],
        [2.27721428, 0.89025812, 1.79050003, 1.48176056, 1.19216589,
         1.56426033],
        [0.93235515, 0.55828101, 1.04758726, 1.00366773, 0.5044303 ,
         1.40030763],
        [1.49310103, 0.94923329, 2.62925703, 2.01916868, 1.57105625,
         1.71293118]])

### 由于原始邻接矩阵上的节点与节点特征矩阵相乘后对自己没有表征，因此加上一个单位矩阵使邻接矩阵对自己有自链接

In [6]:
I = np.eye(A.shape[0])
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
A_hat = A + I
A_hat * node_features

matrix([[1.42373549, 1.17742457, 1.82860386, 1.67791448, 1.43126111,
         1.54669218],
        [2.35133523, 1.19888621, 2.73367216, 2.25229848, 1.63382622,
         2.33874957],
        [1.85995489, 0.57974265, 1.95265556, 1.57805174, 0.70699541,
         2.19236503],
        [2.35133523, 1.19888621, 2.73367216, 2.25229848, 1.63382622,
         2.33874957]])

### 归一化处理

In [8]:
D_hat = np.array(np.sum(A, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))
D_hat

matrix([[2., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 3.]])

In [10]:
((D_hat**-1)*A_hat*node_features).shape

(4, 6)

In [23]:
output_size = 1
w = np.random.rand(4, output_size)

In [24]:
w

array([[0.37230296],
       [0.74428853],
       [0.95903963],
       [0.62034066]])

In [25]:
D_hat**-1*A_hat*node_features * w

ValueError: shapes (4,6) and (4,1) not aligned: 6 (dim 1) != 4 (dim 0)

## LightGCN

## UltraGCN