# All is Graph

Reference:
1. [图卷积网络到底怎么做，这是一份极简的Numpy实现](https://mp.weixin.qq.com/s/sg9O761F0KHAmCPOfMW_kQ)

## Examples

![Cited from [图卷积网络到底怎么做，这是一份极简的Numpy实现](https://mp.weixin.qq.com/s/sg9O761F0KHAmCPOfMW_kQ)](https://mmbiz.qpic.cn/mmbiz_png/KmXPKA19gW8VBwmtdqsNQQEicrmm06aF2OhU65hickwqmthgLOurE3rpdE2MhZhWo7PzfOK4nz3CicDIyfxv8Wl6Q/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

## GCN

In [1]:
import torch
import numpy as np

### 构建邻接矩阵

In [2]:
A = np.matrix([[0, 1, 0, 1],
               [1, 0, 1, 1],
               [0, 1, 0, 1],
               [1, 1, 1, 0]], dtype=float)

In [5]:
node_features = np.random.rand(4, 6)
node_features

array([[0.00438082, 0.76714432, 0.91850695, 0.80540431, 0.25504019,
        0.83894186],
       [0.90780661, 0.65764306, 0.0910929 , 0.28886926, 0.29996668,
        0.92167679],
       [0.86034631, 0.54397293, 0.24822322, 0.72723341, 0.74919585,
        0.78052784],
       [0.86740053, 0.83820027, 0.81457028, 0.63888134, 0.5858439 ,
        0.21855023]])

In [6]:
A * node_features

matrix([[1.77520714, 1.49584332, 0.90566319, 0.9277506 , 0.88581059,
         1.14022702],
        [1.73212766, 2.14931752, 1.98130044, 2.17151907, 1.59007995,
         1.83801993],
        [1.77520714, 1.49584332, 0.90566319, 0.9277506 , 0.88581059,
         1.14022702],
        [1.77253374, 1.96876031, 1.25782306, 1.82150698, 1.30420273,
         2.54114649]])

### 由于原始邻接矩阵上的节点与节点特征矩阵相乘后对自己没有表征，因此加上一个单位矩阵使邻接矩阵对自己有自链接

In [7]:
I = np.eye(A.shape[0])
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
A_hat = A + I
A_hat * node_features

matrix([[1.77958796, 2.26298764, 1.82417013, 1.73315491, 1.14085078,
         1.97916888],
        [2.63993427, 2.80696058, 2.07239335, 2.46038833, 1.89004663,
         2.75969673],
        [2.63555344, 2.03981626, 1.1538864 , 1.65498402, 1.63500644,
         1.92075487],
        [2.63993427, 2.80696058, 2.07239335, 2.46038833, 1.89004663,
         2.75969673]])

### 归一化处理

In [14]:
D_hat = np.array(np.sum(A, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))
D_hat

matrix([[2., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 2., 0.],
        [0., 0., 0., 3.]])

In [17]:
(D_hat**-1)**A_hat*node_features

TypeError: exponent must be an integer

## LightGCN

## UltraGCN